-- ==========================================
-- DAY 5 : VIEWS + INDEXES + QUERY OPTIMIZATION
-- Dataset : OrdersCleaned_UTF8.csv (1,590 rows)
-- Database : day5_views_indexes_optimization
-- ==========================================

-- ==========================================
-- STEP 1 : Database and Table Creation
-- ==========================================

CREATE DATABASE day5_views_indexes_optimization;
\c day5_views_indexes_optimization;

DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    row_index INT,
    id INT,
    name VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(100),
    address TEXT,
    iscod BOOLEAN,
    date_placed TIMESTAMP,
    status VARCHAR(50),
    ivr VARCHAR(50),
    remarks TEXT,
    total NUMERIC,
    date_delivered TIMESTAMP,
    date_returned TIMESTAMP,
    pid VARCHAR(20),
    category VARCHAR(20),
    quantity INT,
    product_name VARCHAR(255)
);

-- ==========================================
-- STEP 2 : Import CSV File
-- ==========================================

\copy orders FROM 'C:/Users/kadam/Downloads/11_day_11_problem/Dataset/OrdersCleaned_UTF8.csv' DELIMITER ',' CSV HEADER ENCODING 'UTF8';

-- ==========================================
-- STEP 3 : Verify Imported Records
-- ==========================================

SELECT COUNT(*) AS total_orders
FROM orders;

-- ==========================================
-- VIEW 1 : Delivered Orders View
-- Purpose : Show only delivered orders
-- ==========================================

CREATE VIEW delivered_orders AS
SELECT *
FROM orders
WHERE status = 'Delivered';

-- Check Delivered Orders Count
SELECT COUNT(*) AS delivered_orders
FROM delivered_orders;

-- ==========================================
-- VIEW 2 : State Revenue View
-- Purpose : Revenue generated by each state
-- ==========================================

CREATE VIEW state_revenue AS
SELECT state,
       SUM(total) AS revenue
FROM orders
GROUP BY state;

-- Top Revenue States Query
SELECT *
FROM state_revenue
ORDER BY revenue DESC
LIMIT 10;

-- ==========================================
-- VIEW 3 : Product Revenue View
-- Purpose : Revenue generated by each product
-- ==========================================

CREATE VIEW product_revenue AS
SELECT product_name,
       SUM(total) AS revenue
FROM orders
GROUP BY product_name;

-- Product Revenue Ranking Query
SELECT *
FROM product_revenue
ORDER BY revenue DESC;

-- ==========================================
-- INDEX 1 : State Index
-- Purpose : Faster search by state
-- ==========================================

CREATE INDEX idx_state
ON orders(state);

-- ==========================================
-- INDEX 2 : Status Index
-- Purpose : Faster search by status
-- ==========================================

CREATE INDEX idx_status
ON orders(status);

-- ==========================================
-- INDEX 3 : Composite Index
-- Purpose : Faster search using state + status
-- ==========================================

CREATE INDEX idx_state_status
ON orders(state, status);

-- ==========================================
-- Check All Created Indexes
-- ==========================================

SELECT *
FROM pg_indexes
WHERE tablename = 'orders';

-- ==========================================
-- Query Optimization Test 1
-- Check execution plan using state filter
-- ==========================================

EXPLAIN ANALYZE
SELECT *
FROM orders
WHERE state = 'Maharashtra';

-- ==========================================
-- Query Optimization Test 2
-- Check execution plan using status filter
-- ==========================================

EXPLAIN ANALYZE
SELECT *
FROM orders
WHERE status = 'Delivered';

-- ==========================================
-- Query Optimization Test 3
-- Composite Index Test
-- ==========================================

EXPLAIN ANALYZE
SELECT *
FROM orders
WHERE state = 'Maharashtra'
AND status = 'Delivered';

-- ==========================================
-- Find Top 10 Highest Value Orders
-- ==========================================

SELECT id,
       name,
       state,
       total
FROM orders
ORDER BY total DESC
LIMIT 10;

-- ==========================================
-- Revenue By Status
-- ==========================================

SELECT status,
       SUM(total) AS revenue
FROM orders
GROUP BY status
ORDER BY revenue DESC;

-- ==========================================
-- BONUS 1 : View Update / Sample Check
-- ==========================================

SELECT *
FROM delivered_orders
LIMIT 10;

-- ==========================================
-- BONUS 2 : Before vs After Index Performance
-- ==========================================

EXPLAIN ANALYZE
SELECT *
FROM orders
WHERE state = 'Karnataka';

-- ==========================================
-- BONUS 3 : Top 5 Revenue Products View
-- ==========================================

SELECT product_name,
       revenue
FROM product_revenue
ORDER BY revenue DESC
LIMIT 5;

-- ==========================================
-- DAY 5 COMPLETE
-- Concepts Covered:
-- 1. CREATE VIEW
-- 2. CREATE INDEX
-- 3. Composite Index
-- 4. Query Optimization
-- 5. EXPLAIN ANALYZE
-- ==========================================
